In [9]:
import numpy as np
import pandas as pd
import seaborn as sns 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.datasets import fetch_california_housing
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [10]:
data = fetch_california_housing(as_frame=True)

In [11]:
df = pd.concat([data.data, data.target.rename('MedHouseVal')], axis=1)
df.head()

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422

In [12]:
Y = df['MedHouseVal']
X = df.drop(labels="MedHouseVal",axis=1)

In [13]:
X

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [14]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()      
X_scaled = scaler.fit_transform(X)

In [15]:
x_train, x_test, Y_train, Y_test = train_test_split(
    X_scaled,
    Y,
    test_size=0.2,
    random_state=42
)

print(x_train.shape)
print(x_test.shape)
print(Y_train.shape)
print(Y_test.shape)

(16512, 8)
(4128, 8)
(16512,)
(4128,)

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(),
    "Ridge Regression": Ridge(alpha=1.0)
}

In [17]:
import numpy as np
import pandas as pd

from sklearn.metrics import mean_squared_error, r2_score


results = {}


for name, model in models.items():

    
    model.fit(x_train, Y_train)

    
    y_pred = model.predict(x_test)

   
    rmse = np.sqrt(mean_squared_error(Y_test, y_pred))
    r2 = r2_score(Y_test, y_pred)

   
    results[name] = {
        "RMSE": rmse,
        "R2 Score": r2
    }


results_df = pd.DataFrame(results).T


results_df = results_df.sort_values(by="R2 Score", ascending=False)

print(results_df)

                       RMSE  R2 Score
Decision Tree      0.707480  0.618037
Ridge Regression   0.745554  0.575819
Linear Regression  0.745581  0.575788

In [18]:
import numpy as np
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_squared_error

# Create the model (high chance of overfitting)
model = DecisionTreeRegressor(max_depth=None, random_state=42)

# Train the model
model.fit(x_train, Y_train)

# Predictions
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

# R2 Scores
train_r2 = r2_score(Y_train, train_pred)
test_r2 = r2_score(Y_test, test_pred)

# RMSE
train_rmse = np.sqrt(mean_squared_error(Y_train, train_pred))
test_rmse = np.sqrt(mean_squared_error(Y_test, test_pred))

print("Decision Tree Regressor")
print("Train R2 Score :", train_r2)
print("Test R2 Score  :", test_r2)
print("Train RMSE     :", train_rmse)
print("Test RMSE      :", test_rmse)

# Check Overfitting
if train_r2 > test_r2 + 0.10:
    print("\nModel is OVERFITTING")
else:
    print("\nModel is not significantly overfitting")

Decision Tree Regressor
Train R2 Score : 1.0
Test R2 Score  : 0.6228111330554302
Train RMSE     : 3.218325866275131e-16
Test RMSE      : 0.7030445773467542

Model is OVERFITTING

In [19]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error

# Create the model (high chance of overfitting)
model = LinearRegression()

# Train the model
model.fit(x_train, Y_train)

# Predictions
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

# R2 Scores
train_r2 = r2_score(Y_train, train_pred)
test_r2 = r2_score(Y_test, test_pred)

# RMSE
train_rmse = np.sqrt(mean_squared_error(Y_train, train_pred))
test_rmse = np.sqrt(mean_squared_error(Y_test, test_pred))

print("Linear Regressor ")
print("Train R2 Score :", train_r2)
print("Test R2 Score  :", test_r2)
print("Train RMSE     :", train_rmse)
print("Test RMSE      :", test_rmse)

# Check Overfitting
if train_r2 > test_r2 + 0.10:
    print("\nModel is OVERFITTING")
else:
    print("\nModel is not significantly overfitting")

Linear Regressor
Train R2 Score : 0.6125511913966952
Test R2 Score  : 0.575787706032451
Train RMSE     : 0.7196757085831575
Test RMSE      : 0.7455813830127762

Model is not significantly overfitting

In [20]:
import numpy as np
from sklearn.linear_model import Ridge
from sklearn.metrics import r2_score, mean_squared_error

# Create the model (high chance of overfitting)
model = Ridge(alpha=1.0)

# Train the model
model.fit(x_train, Y_train)

# Predictions
train_pred = model.predict(x_train)
test_pred = model.predict(x_test)

# R2 Scores
train_r2 = r2_score(Y_train, train_pred)
test_r2 = r2_score(Y_test, test_pred)

# RMSE
train_rmse = np.sqrt(mean_squared_error(Y_train, train_pred))
test_rmse = np.sqrt(mean_squared_error(Y_test, test_pred))

print("Ridge Regressor")
print("Train R2 Score :", train_r2)
print("Test R2 Score  :", test_r2)
print("Train RMSE     :", train_rmse)
print("Test RMSE      :", test_rmse)

# Check Overfitting
if train_r2 > test_r2 + 0.10:
    print("\nModel is OVERFITTING")
else:
    print("\nModel is not significantly overfitting")

Ridge Regressor
Train R2 Score : 0.612551119993334
Test R2 Score  : 0.5758185345441325
Train RMSE     : 0.7196757748980629
Test RMSE      : 0.7455542909384607

Model is not significantly overfitting

In [25]:
## LIMIT TREE DEPTH
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score

# Controlled Decision Tree
controlled_model = DecisionTreeRegressor(
    max_depth=5,
    random_state=42
)

controlled_model.fit(x_train, Y_train)

train_pred = controlled_model.predict(x_train)
test_pred = controlled_model.predict(x_test)

train_r2 = r2_score(Y_train, train_pred)
test_r2 = r2_score(Y_test, test_pred)

print("After Controlling Overfitting")
print("Train R2:", train_r2)
print("Test R2 :", test_r2)

After Controlling Overfitting
Train R2: 0.6376786573648903
Test R2 : 0.5997321244428706

In [29]:
#Comparing before and after the limit depth tree
import pandas as pd

comparison = pd.DataFrame({
    "Model": ["Original Decision Tree", "Controlled Decision Tree"],
    "Train R2": [1.00, train_r2],
    "Test R2": [0.62, test_r2]
})

print(comparison)

                      Model  Train R2   Test R2
0    Original Decision Tree  1.000000  0.620000
1  Controlled Decision Tree  0.637679  0.599732

In [31]:
## Cross Validation
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    controlled_model,
    X,
    Y,
    cv=5,
    scoring='r2'
)

print("Cross Validation Scores:", cv_scores)
print("Average CV R2:", cv_scores.mean())

Cross Validation Scores: [0.32603463 0.52499182 0.60290742 0.31954034 0.53355785]
Average CV R2: 0.46140641222621015

In [32]:
#Hyper parameter tuning
from sklearn.model_selection import GridSearchCV

param_grid = {
    'max_depth': [3, 5, 7, 10],
    'min_samples_split': [2, 5, 10]
}

grid = GridSearchCV(
    DecisionTreeRegressor(random_state=42),
    param_grid,
    cv=5,
    scoring='r2'
)

grid.fit(x_train, Y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV Score:", grid.best_score_)

Best Parameters: {'max_depth': 10, 'min_samples_split': 10}
Best CV Score: 0.6965681952293667

In [33]:
best_model = grid.best_estimator_

y_pred = best_model.predict(x_test)

r2 = r2_score(Y_test, y_pred)
rmse = np.sqrt(mean_squared_error(Y_test, y_pred))

print("rmse  :", rmse)
print("r2  :", r2)

rmse  : 0.6454300828015771
r2  : 0.6820992539714815

In [34]:
import pickle

# Train your model first
model.fit(x_train, Y_train)

# Save model
with open("trained_model.pkl", "wb") as file:
    pickle.dump(model, file)

print("Model saved successfully!")

Model saved successfully!

In [36]:
import pickle

with open("trained_model.pkl", "rb") as file:
    model = pickle.load(file)

print("Model loaded successfully!")

Model loaded successfully!